services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: order_api
      POSTGRES_USER: order_api
      POSTGRES_PASSWORD: order_api
    ports:
      - "5432:5432"
    volumes:
      - order-api-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_api -d order_api"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  order-api-postgres-data:
